info:
  artifact: ${project.artifactId}
  name: ${spring.application.name}
  description: ${project.description}
  version: ${project.version}

eureka:
  enableSelfPreservation: true
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 2
    instanceEnabledOnit: true
  instance:
   preferIpAddress: true